<script setup>
import { toRef, computed } from "vue";
const props = defineProps({
	value: [String, Number],
	history: String,
	isDark: Boolean,
});
const value = toRef(props, "value");

// Dynamic font size based on content length
// Generated by Github Copilot
const fontSize = computed(() => {
	const length = String(props.value).length;
	if (length <= 8) return "48px";
	if (length <= 10) return "42px";
	if (length <= 12) return "36px";
	if (length <= 15) return "30px";
	if (length <= 18) return "24px";
	return "20px";
});
</script>

<template>
	<div class="display" :class="{ dark: props.isDark }">
		<div class="history" v-if="props.history">{{ props.history }}</div>
		<div class="value" :style="{ fontSize: fontSize }">{{ value }}</div>
	</div>
</template>

<style scoped>
.display {
	background: transparent;
	padding: 20px 20px 16px;
	min-height: 120px;
	display: flex;
	flex-direction: column;
	justify-content: flex-end;
	align-items: flex-end;
	text-align: right;
}

.history {
	font-size: 14px;
	color: rgba(0, 0, 0, 0.6);
	margin-bottom: 8px;
	font-family: "Segoe UI", "Segoe UI Web", "Segoe UI Symbol", -apple-system, BlinkMacSystemFont, sans-serif;
	font-weight: 400;
}

.display.dark .history {
	color: rgba(255, 255, 255, 0.6);
}

.value {
	font-size: 48px; /* Default, overridden by dynamic sizing */
	font-weight: 600;
	line-height: 1.1;
	color: #000000;
	font-family: "Segoe UI", "Segoe UI Web", "Segoe UI Symbol", -apple-system, BlinkMacSystemFont, sans-serif;
	word-break: keep-all;
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
	max-width: 100%;
	min-width: 0;
	letter-spacing: -0.5px;
	direction: rtl;
	text-align: left;
}

.display.dark .value {
	color: #ffffff;
}

/* Ensure proper font scaling on smaller screens */
@media (max-width: 400px) {
	.value {
		letter-spacing: -0.25px;
	}
}

/* For very long numbers, show the end (most significant digits) */
.value {
	unicode-bidi: plaintext;
}
</style>
